# Install dependencies
install:
    pip install -r requirements.txt

# Run the Flask app
run:
    FLASK_APP=server/src/application/app.py flask run

# Run tests
test:
    pytest

# Clean the environment
clean:
    rm -rf __pycache__/
