### Get moods
GET http://localhost:5000/v1/moods
Accept: application/json

### Get mood 
GET http://localhost:5000/v1/moods/1c5709dc-bced-45a5-912f-17f25c354403
Accept: application/json

### Create mood
POST http://localhost:5000/v1/moods
Content-Type: application/json

{
    "date": "2023-03-18T15:00:41",
    "feeling": "happy",
    "intensity": 5,
    "comments": "Lorem ipsum dolor comment",
    "activity": "Lorem ipsum dolor activity"
}


### Update mood
PUT http://localhost:5000/v1/moods/860be9a5-a48b-4c40-ad04-fde0313f7a72
Content-Type: application/json

{
    "date": "2023-03-18T15:00:41",
    "feeling": "happy",
    "intensity": 5,
    "comments": "It's changed comments",
    "activity": "It's a brand new changed activity"
}

### Delete mood
DELETE http://localhost:5000/v1/moods/860be9a5-a48b-4c40-ad04-fde0313f7a72
Content-Type: application/json
