### Get moods
GET http://localhost:5000/v1/moods
Accept: application/json

### Get mood 
GET http://localhost:5000/v1/moods/b10fe89d-41e8-4669-8cc7-f50d540710c6
Accept: application/json

### Create mood
POST http://localhost:5000/v1/moods
Content-Type: application/json

{
    "date": "2023-03-18T15:00:41",
    "feeling": "happy",
    "intensity": 5,
    "comments": "Lorem ipsum dolor comment",
    "activity": "Lorem ipsum dolor activity"
}


### Update mood
PUT http://localhost:5000/v1/moods/b10fe89d-41e8-4669-8cc7-f50d540710c6
Content-Type: application/json

{
    "date": "2023-03-18T15:00:41",
    "feeling": "happy",
    "intensity": 5,
    "comments": "It's changed comments",
    "activity": "It's a brand new changed activity"
}

### Delete mood
DELETE http://localhost:5000/v1/moods/860be9a5-a48b-4c40-ad04-fde0313f7a72
Content-Type: application/json
